spring:
  application:
    name: facade
jwt:
  secret: spring

server:
  port: 8091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
