spring:
  application:
    name: notification-service
  rabbitmq:
    host: rabbitmq
    port: 15672
    username: guest
    password: guest
server:
  port: 8099
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
